# Generated by Django 4.1.6 on 2023-02-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField(max_length=500)),
                ('ans', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
