# Generated by Django 4.1.6 on 2023-02-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_banner_remove_product_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=30, unique=True),
        ),
    ]
