# Generated by Django 4.1.6 on 2023-02-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='products/banner_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
