# Generated by Django 4.1.6 on 2023-02-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
