# Generated by Django 4.1.6 on 2023-02-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_review_reviewcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewcomment',
            options={'ordering': ('created_at',)},
        ),
    ]
