# Generated by Django 4.1.6 on 2023-02-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_wishlist_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='subtotal',
        ),
    ]
