# Generated by Django 4.1.6 on 2023-02-22 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
