# Generated by Django 4.1.6 on 2023-02-20 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='rate',
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.product'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
